%%{init:
    {
        'theme': 'default',
        'themeCSS': '.actorText, .messageText, .noteText { font-size: 22px !important; }'
    }
}%%
gantt
    %% title Timeline to Finish PhD
    dateFormat YYYY-MM-DD
    axisFormat %m-%y
    todayMarker off
    tickInterval 1month

section Property<br/>Graph<br/>Model
    Inline Properties: t1, 2024-07-15, 2024-07-31
    Column-Store for Properties: t2, 2024-08-01, 2024-09-01
    Evaluation against GraphDBs: t3, 2024-09-01, 2024-10-15

section Dynamic<br/>Graph<br/>Evaluation
    Finish Grafaree: t1, 2024-06-16, 2024-07-20
    Evaluation using Grafaree: t2, 2024-07-21, 2024-08-15

section Specialized<br/>Indexing<br/>for Graphs 
    Reading: t1, 2024-09-01, 2024-10-15
    Implement: t2, 2024-10-16, 2024-12-15

section Administrative<br/>Deadlines
    Writing the Dissertation: t1, 2024-12-15, 2025-04-15
    Appointment of External Examiner  :milestone, 2025-02-13, 2025-02-15
    Dissertation submission  :milestone, 2025-04-14, 2025-04-16
    Defense  :milestone, 2025-05-31, 2025-06-02
    Dissertation Approval :milestone, 2025-07-14, 2025-07-16
    Graduation 🎓  :milestone, 2025-11-26, 2025-11-28